### ISSUE TITLE
Tema 6 - Estrutura de dados

### ISSUE THREAD

**Issue by mateus-azevedo** [viniciusoliveiras/uni-TI#2]
- [x] Usuário insere o item dinamicamente
- [x] Refatorar Código 
- [x] Excluir a função e o protótipo da função height da [main.c](https://github.com/viniciusoliveiras/uni-TI/blob/main/866%20-%20Estrutura%20de%20Dados/Tema%206/main.c)
- [x] Excluir TAD Pilha e Filas https://github.com/viniciusoliveiras/uni-TI/blob/e91ac225a92436aed8516398da167b251cf72f94/866%20-%20Estrutura%20de%20Dados/Tema%206/TAD_arvore_binaria_aloc_enc.h#L73-L117
- [x] Excluir arquivos [pilha.c](https://github.com/viniciusoliveiras/uni-TI/blob/main/866%20-%20Estrutura%20de%20Dados/Tema%206/pilha.c) e [fila.c](https://github.com/viniciusoliveiras/uni-TI/blob/main/866%20-%20Estrutura%20de%20Dados/Tema%206/fila.c)

**Comment by Rhuan-Gonzaga** [comment]
Beleza
